pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    stages {
        stage('Build maven project') {
            steps {
                checkout scmGit(
                    branches: [[name: '*/main']],
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/ilyushik/DailyLog']])
                dir('Back-end/SpringApp') {
                    sh 'mvn clean install'
                }
            }
        }
        stage('Build Docker image') {
            steps {
                dir('Back-end/SpringApp') {
                    sh 'docker build -t kamaraliilya/dailylog_backend:latest .'
                }
            }
        }
        stage('Push docker image to docker hub') {
            steps {
                withCredentials([string(credentialsId: 'docker_pwd', variable: 'dockerhubpwd')]) {
                    sh 'docker login -u kamaraliilya -p ${dockerhubpwd}'
                    sh 'docker push kamaraliilya/dailylog_backend:latest'
                }
            }
        }
    }
}
